spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:foodie}
    username: ${DB_USER:foodie}
    password: ${DB_PASSWORD:foodie}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  flyway:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        type:
          preferred_enum_jdbc_type: VARCHAR
    hibernate:
      ddl-auto: update

logging:
  level:
    com.foodie: DEBUG
    org.springframework.security: INFO

management:
  endpoint:
    health:
      show-details: always
