package com.foodie.common.enums;

public enum OrderStatus {
    PENDING_PAYMENT,
    PLACED,
    CONFIRMED,
    ACCEPTED,
    PREPARING,
    WAITING_FOR_DELIVERY_PARTNER,
    READY_FOR_PICKUP,
    ASSIGNED,
    REACHED_RESTAURANT,
    PICKED_UP,
    OUT_FOR_DELIVERY,
    DELIVERED,
    REJECTED,
    CANCELLED
}
