ALTER TABLE "order" DROP CONSTRAINT IF EXISTS chk_order_status;
ALTER TABLE "order" ADD CONSTRAINT chk_order_status CHECK (status IN (
    'PENDING_PAYMENT', 'PLACED', 'CONFIRMED', 'ACCEPTED', 'PREPARING', 'READY_FOR_PICKUP',
    'ASSIGNED', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED',
    'REJECTED', 'CANCELLED'
));
