ALTER TABLE delivery_partner
  ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(500),
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(500),
  ADD COLUMN IF NOT EXISTS city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS state VARCHAR(100),
  ADD COLUMN IF NOT EXISTS pincode VARCHAR(20);
